name: Recieve repository dispatch event
on:
    repository_dispatch: 
        types:
            - dispatch-event

jobs:
    trigger-workflow:
        name: Trigger workflow based on the event
        runs-on: self-hosted
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Modify the test file
          working-directory: apps/inventory
          run: |
            echo ${{ github.event.client_payload.message }} > test.txt